// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const addSearchTabToNav: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/navigation').addSearchTabToNav
  const applyRecipieFinderTheme: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/theme').applyRecipieFinderTheme
  const browser: typeof import('wxt/browser').browser
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const decrementSearchRemaining: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/search').decrementSearchRemaining
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const displayApiKeyError: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/ui').displayApiKeyError
  const displaySearchBox: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/ui').displaySearchBox
  const displaySearchResults: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/ui').displaySearchResults
  const escapeHtml: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/ui').escapeHtml
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const fetchAndExtractApiKey: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/api').fetchAndExtractApiKey
  const filterProjects: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/search').filterProjects
  const getActiveFilters: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/search').getActiveFilters
  const getSearchRemaining: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/search').getSearchRemaining
  const handleExploreTabRedirect: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/navigation').handleExploreTabRedirect
  const hideExploreContent: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/navigation').hideExploreContent
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const modifyExplorePage: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/navigation').modifyExplorePage
  const searchProjects: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/api').searchProjects
  const storage: typeof import('wxt/utils/storage').storage
  const updateSearchRemaining: typeof import('C:/Users/Kai/OneDrive - education.wa.edu.au/Documents/thecheffskiss/utils/search').updateSearchRemaining
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
}
